Repository GuilhermeFernandes01/sin5005-appx, pull requests merged in 2024-10, with the labels that each got.

#27 Ingredientes - #1 - Quantidade Mínima e Máxima de Estoque
  app/controllers/ingredients_controller.rb
  app/models/ingredient.rb
  app/views/ingredients/_form.html.erb
  app/views/ingredients/_ingredient.html.erb
  app/views/ingredients/_ingredient.json.jbuilder
  db/migrate/20241006223236_add_quantity_stock_min_max_to_ingredients.rb
  db/schema.rb
  features/create_ingredients.feature
  features/step_definitions/create_ingredients_steps.rb
  spec/controllers/ingredient_controller_spec.rb
  spec/factories/ingredients.rb
  spec/models/ingredient_spec.rb
  spec/views/ingredients/edit.html.erb_spec.rb
  spec/views/ingredients/index.html.erb_spec.rb
  spec/views/ingredients/show.html.erb_spec.rb
Labels: iteração-2

#29 Leo
  app/controllers/clientes_controller.rb
  app/models/cliente.rb
  app/views/clientes/edit.html.erb
  app/views/clientes/index.html.erb
  app/views/clientes/new.html.erb
  app/views/clientes/show.html.erb
  db/development.sqlite3
  db/migrate/20241007132238_add_data_nascimento_to_clientes.rb
  db/schema.rb
  features/cliente_contagem.feature
  features/clientes_aniversario.feature
  features/step_definitions/cadastro_cliente_steps.rb
  features/step_definitions/clientes_aniversario_steps.rb
  features/step_definitions/clientes_contagem_steps.rb
  report.html
  spec/models/cliente_spec.rb
Labels: iteração-2

#36 Rodar migrations a cada novo deploy no Heroku
  Procfile
Labels: iteração-3

#33 #Ingredients - Filters - All - Less Than Stock Min. - Greater Than Stock Min.
  app/controllers/ingredients_controller.rb
  app/views/ingredients/index.html.erb
  features/filters_ingredients.feature
  features/step_definitions/filters_ingredients_steps.rb
  spec/controllers/ingredient_controller_spec.rb
Labels: iteração-3

#42 Ingredients Filter by Name
  app/controllers/ingredients_controller.rb
  app/views/ingredients/index.html.erb
  features/filter_ingredients_by_name.feature
  features/step_definitions/filter_ingredients_by_name.rb
  spec/controllers/ingredient_controller_spec.rb
Labels: iteração-3

#35 Atualiza funcionários; permite demissão de funcionários; padroniza estilos de formulário
  .coveralls.yml
  app/assets/stylesheets/application.scss
  app/controllers/employees_controller.rb
  app/views/clientes/edit.html.erb
  app/views/clientes/new.html.erb
  app/views/employees/_employee.html.erb
  app/views/employees/_employee_not_found.html.erb
  app/views/employees/_form_edit_employee.html.erb
  app/views/employees/_form_new_employee.html.erb
  app/views/employees/edit.html.erb
  app/views/employees/index.html.erb
  app/views/employees/new.html.erb
  app/views/employees/show.html.erb
  app/views/ingredients/_form.html.erb
  app/views/ingredients/edit.html.erb
  app/views/ingredients/new.html.erb
  app/views/layouts/application.html.erb
  app/views/products/new.html.erb
  app/views/suppliers/new.html.erb
  config/credentials.yml.enc
  config/routes.rb
  features/create_employee.feature
  features/list_employees.feature
  features/show_employee.feature
  features/step_definitions/create_employee_steps.rb
  features/step_definitions/employee_steps.rb
  features/step_definitions/list_employees_steps.rb
  features/step_definitions/show_employee_steps.rb
  spec/controllers/employees_controller_spec.rb
  spec/factories/employees.rb
  spec/requests/employees_spec.rb
Labels: iteração-2, iteração-3

#55 Menu Navegação
  app/views/layouts/application.html.erb
  features/menu_navegacao.feature
  features/step_definitions/menu_navegacao_steps.rb
Labels: iteração-4
